apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: KubernetesPractice
spec:
  selector:
    matchLabels:
      app: KubernetesPractice
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: KubernetesPractice
    spec:
      containers:
        - name: KubernetesPractice
          image: kubernetespractice:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
# The port that the container is running on in the cluster